# DEFINITIONS HOW THE TABLES IN THIS FOLDER SHOULD BE

version: 2

sources:
  - name: nhl_raw
    database: postgres
    schema: nhl_raw
    tables:
    - name: raw_player_info
      description: "Player information and stats for latest season and all time career wise"
    - name: raw_all_team_stats
      description: "All stats from teams across all seasons"
    - name: raw_all_skaters_stats
      description: "All stats from skaters across all seasons"
    - name: raw_all_goalies_stats
      description: "All stats from goalies across all seasons"
    - name: raw_all_game_log
      description: "Player stats for all players per game"
    - name: raw_roster_season
      description: "Player information per team each season"
    - name: raw_all_club_stats
      description: "All stats from skaters across all seasons per team"
    - name: raw_play_by_play
      description: "All plays during a game"
    - name: raw_game_info
      description: "All games summary info - FACT"

####################################################################################################################

models:
  - name: stg_csv__player_info
    columns:
      - name: player_id
        description: "Primary key for player dimension"
        tests:
          - not_null
          - unique

  - name: stg_csv__all_team_stats
    description: "Contains all stats for each season - SDC"
    columns:
      - name: team_id
        tests:
          - not_null
      - name: team_name
        tests:
          - not_null

  - name: stg_csv__all_skaters_stats
    description: "Contains all stats for each season - SDC"
    columns:
      - name: player_id
        description: "Unique identifier for player"
        tests:
          - not_null
      - name: pk
        description: "Unique row identifider with player_id+season_id"
        tests:
          - not_null
          - unique

  - name: stg_csv__all_goalies_stats
    description: "Contains all stats for per season - SDC"
    columns:
      - name: player_id
        description: "Unique identifier for player"
        tests:
          - not_null
      - name: pk
        description: "Unique row identifider with player_id+season_id"
        tests:
          - not_null
          - unique

  - name: stg_csv__all_game_log
    description: "Fact table containing game stats for every player per game"
    columns:
      - name: pk
        description: "Unique row identifier with game_id+player_id"
        tests:
          - not_null
          - unique

  - name: stg_csv__roster_season
    description: "Contains player info across seasons and their team"
    columns:
      - name: pk
        description: "Unique row identifier with game_id + player_id + team_id"
        tests:
          - not_null
          - unique
      - name: player_id
        description: "Unique identifier for player"
        tests:
          - not_null
