with source as (
        select * from {{ source('nhl_raw', 'raw_player_info') }}
  ),
renamed as (
    select
    {{ string_to_int('playerid') }} as player_id,
    firstname_default as first_name,
    lastname_default as last_name,
    concat(firstname_default,' ',lastname_default) as full_name,
    isactive:: bool as is_active,
    {{ string_to_int('sweaternumber') }}  as jersey_number,
    position,
    headshot as pic_url,
    {{ string_to_int('heightininches') }} as height_inches,
    {{ string_to_int('weightinpounds') }} as weight_pounds,
    {{ string_to_int('heightincentimeters') }} as height_centimeters,
    {{ string_to_int('weightinkilograms') }} as weight_kg,
    to_date(birthdate, 'yyyy-mm-dd') as birth_date,
    birthcountry as birth_country,
    birthcity_default as birth_city,
    birthstateprovince_default as birth_state,
    shootscatches as shoots_or_catches,
    intop100alltime::bool as in_top100_alltime,
    inhhof:: bool as in_hall_of_fame,
    {{ string_to_int('featuredstats_season') }} as latest_season,
    currentteamabbrev as current_team_trid,
    {{ string_to_int('draftdetails_overallpick') }} as  draft_overall_pick,
    {{ string_to_int('draftdetails_pickinround') }} as  draft_pickinround,
    {{ string_to_int('draftdetails_round') }} as  draft_round,
    draftdetails_teamabbrev as  draft_team_id,
    {{ string_to_int('draftdetails_year') }} as  draft_year,
    {{ string_to_int('careertotals_playoffs_assists') }} as  career_pos_assists,
    {{ string_to_sec('careertotals_playoffs_avgtoi') }} as  career_pos_avg_timeonice_seconds, -- rever
    {{ string_to_float('careertotals_playoffs_faceoffwinningpctg') }} as  career_pos_faceoff_winning_pctg, -- rever
    {{ string_to_int('careertotals_playoffs_gamesplayed') }} as  career_pos_games_played,
    {{ string_to_int('careertotals_playoffs_gamesstarted') }} as  career_pos_games_started,
    {{ string_to_int('careertotals_playoffs_gamewinninggoals') }} as  career_pos_game_winning_goals,
    {{ string_to_int('careertotals_playoffs_goals') }} as  career_pos_goals,
    {{ string_to_int('careertotals_playoffs_goalsagainst') }} as  career_pos_goals_against,
    {{ string_to_float('careertotals_playoffs_goalsagainstavg') }} as  career_pos_goals_against_avg,
    {{ string_to_int('careertotals_playoffs_losses') }} as  career_pos_losses,
    {{ string_to_int('careertotals_playoffs_otgoals') }} as  career_pos_ot_goals,
    {{ string_to_int('careertotals_playoffs_otlosses') }} as  career_pos_ot_losses,
    {{ string_to_int('careertotals_playoffs_pim') }} as  career_pos_pim,
    {{ string_to_int('careertotals_playoffs_plusminus') }} as  career_pos_plus_minus,
    {{ string_to_int('careertotals_playoffs_points') }} as  career_pos_points,
    {{ string_to_int('careertotals_playoffs_powerplaygoals') }} as  career_pos_powerplay_goals,
    {{ string_to_int('careertotals_playoffs_powerplaypoints') }} as  career_pos_powerplay_points,
    {{ string_to_float('careertotals_playoffs_savepctg') }} as  career_pos_save_pctg, -- rever
    {{ string_to_float('careertotals_playoffs_shootingpctg') }} as  career_pos_shooting_pctg, -- rever
    {{ string_to_int('careertotals_playoffs_shorthandedgoals') }} as  career_pos_shorthanded_goals,
    {{ string_to_int('careertotals_playoffs_shorthandedpoints') }} as  career_pos_shorthanded_points,
    {{ string_to_int('careertotals_playoffs_shots') }} as  career_pos_shots,
    {{ string_to_int('careertotals_playoffs_shotsagainst') }} as  career_pos_shotsagainst,
    {{ string_to_int('careertotals_playoffs_shutouts') }} as  career_pos_shutouts,
    {{ string_to_int('careertotals_playoffs_ties') }} as  career_pos_ties,
    {{ string_to_sec('careertotals_playoffs_timeonice') }} as  career_pos_timeonice_seconds, -- rever
    {{ string_to_int('careertotals_playoffs_wins') }} as  career_pos_wins,
    {{ string_to_int('careertotals_regularseason_assists') }} as  career_reg_assists,
    {{ string_to_sec('careertotals_regularseason_avgtoi') }} as  career_reg_avg_timeonice_seconds, -- rever
    {{ string_to_float('careertotals_regularseason_faceoffwinningpctg') }} as  career_reg_faceoff_winning_pctg, -- rever
    {{ string_to_int('careertotals_regularseason_gamesplayed') }} as  career_reg_games_played,
    {{ string_to_int('careertotals_regularseason_gamesstarted') }} as  career_reg_games_started,
    {{ string_to_int('careertotals_regularseason_gamewinninggoals') }} as  career_reg_game_winning_goals,
    {{ string_to_int('careertotals_regularseason_goals') }} as  career_reg_goals,
    {{ string_to_int('careertotals_regularseason_goalsagainst') }} as  career_reg_goals_against,
    {{ string_to_float('careertotals_regularseason_goalsagainstavg') }} as  career_reg_goals_against_avg,
    {{ string_to_int('careertotals_regularseason_losses') }} as  career_reg_losses,
    {{ string_to_int('careertotals_regularseason_otgoals') }} as  career_reg_ot_goals,
    {{ string_to_int('careertotals_regularseason_otlosses') }} as  career_reg_ot_losses,
    {{ string_to_int('careertotals_regularseason_pim') }} as  career_reg_pim,
    {{ string_to_int('careertotals_regularseason_plusminus') }} as  career_reg_plus_minus,
    {{ string_to_int('careertotals_regularseason_points') }} as  career_reg_points,
    {{ string_to_int('careertotals_regularseason_powerplaygoals') }} as  career_reg_powerplay_goals,
    {{ string_to_int('careertotals_regularseason_powerplaypoints') }} as  career_reg_powerplay_points,
    {{ string_to_float('careertotals_regularseason_savepctg') }} as  career_reg_savepctg, -- rever
    {{ string_to_float('careertotals_regularseason_shootingpctg') }} as  career_reg_shootingpctg, -- rever
    {{ string_to_int('careertotals_regularseason_shorthandedgoals') }} as  career_reg_shorthanded_goals,
    {{ string_to_int('careertotals_regularseason_shorthandedpoints') }} as  career_reg_shorthanded_points,
    {{ string_to_int('careertotals_regularseason_shots') }} as  career_reg_shots,
    {{ string_to_int('careertotals_regularseason_shotsagainst') }} as  career_reg_shots_against,
    {{ string_to_int('careertotals_regularseason_shutouts') }} as  career_reg_shutouts,
    {{ string_to_int('careertotals_regularseason_ties') }} as  career_reg_ties,
    {{ string_to_sec('careertotals_regularseason_timeonice') }} as  career_reg_timeonice_seconds, -- rever
    {{ string_to_int('careertotals_regularseason_wins') }} as  career_reg_wins,
    {{ string_to_int('featuredstats_playoffs_subseason_assists') }} as  ls_pos_assists,
    {{ string_to_int('featuredstats_playoffs_subseason_gamesplayed') }} as  ls_pos_games_played,
    {{ string_to_int('featuredstats_playoffs_subseason_gamewinninggoals') }} as  ls_pos_game_winning_goals,
    {{ string_to_int('featuredstats_playoffs_subseason_goals') }} as  ls_pos_goals,
    {{ string_to_float('featuredstats_playoffs_subseason_goalsagainstavg') }} as  ls_pos_goals_against_avg,
    {{ string_to_int('featuredstats_playoffs_subseason_losses') }} as  ls_pos_losses,
    {{ string_to_int('featuredstats_playoffs_subseason_otgoals') }} as  ls_pos_ot_goals,
    {{ string_to_int('featuredstats_playoffs_subseason_otlosses') }} as  ls_pos_ot_losses,
    {{ string_to_int('featuredstats_playoffs_subseason_pim') }} as  ls_pos_pim,
    {{ string_to_int('featuredstats_playoffs_subseason_plusminus') }} as  ls_pos_plusminus,
    {{ string_to_int('featuredstats_playoffs_subseason_points') }} as  ls_pos_points,
    {{ string_to_int('featuredstats_playoffs_subseason_powerplaygoals') }} as  ls_pos_powerplay_goals,
    {{ string_to_int('featuredstats_playoffs_subseason_powerplaypoints') }} as  ls_pos_powerplay_points,
    {{ string_to_float('featuredstats_playoffs_subseason_savepctg') }} as  ls_pos_save_pctg, -- rever
    {{ string_to_float('featuredstats_playoffs_subseason_shootingpctg') }} as  ls_pos_shooting_pctg,
    {{ string_to_int('featuredstats_playoffs_subseason_shorthandedgoals') }} as  ls_pos_shorthanded_goals,
    {{ string_to_int('featuredstats_playoffs_subseason_shorthandedpoints') }} as  ls_pos_shorthanded_points,
    {{ string_to_int('featuredstats_playoffs_subseason_shots') }} as  ls_pos_shots,
    {{ string_to_int('featuredstats_playoffs_subseason_shutouts') }} as  ls_pos_shutouts,
    {{ string_to_int('featuredstats_playoffs_subseason_ties') }} as  ls_pos_ties,
    {{ string_to_int('featuredstats_playoffs_subseason_wins') }} as  ls_pos_wins,
    {{ string_to_int('featuredstats_regularseason_subseason_assists') }} as  ls_reg_assists,
    {{ string_to_int('featuredstats_regularseason_subseason_gamesplayed') }} as  ls_reg_games_played,
    {{ string_to_int('featuredstats_regularseason_subseason_gamewinninggoals') }} as  ls_reg_game_winning_goals,
    {{ string_to_int('featuredstats_regularseason_subseason_goals') }} as  ls_reg_goals,
    {{ string_to_float('featuredstats_regularseason_subseason_goalsagainstavg') }} as  ls_reg_goals_against_avg,
    {{ string_to_int('featuredstats_regularseason_subseason_losses') }} as  ls_reg_losses,
    {{ string_to_int('featuredstats_regularseason_subseason_otgoals') }} as  ls_reg_ot_goals,
    {{ string_to_int('featuredstats_regularseason_subseason_otlosses') }} as  ls_reg_ot_losses,
    {{ string_to_int('featuredstats_regularseason_subseason_pim') }} as  ls_reg_pim,
    {{ string_to_int('featuredstats_regularseason_subseason_plusminus') }} as  ls_reg_plusminus,
    {{ string_to_int('featuredstats_regularseason_subseason_points') }} as  ls_reg_points,
    {{ string_to_int('featuredstats_regularseason_subseason_powerplaygoals') }} as  ls_reg_powerplay_goals,
    {{ string_to_int('featuredstats_regularseason_subseason_powerplaypoints') }} as  ls_reg_powerplay_points,
    {{ string_to_float('featuredstats_regularseason_subseason_savepctg') }} as  ls_reg_save_pctg,
    {{ string_to_float('featuredstats_regularseason_subseason_shootingpctg') }} as  ls_reg_shooting_pctg, -- rever
    {{ string_to_int('featuredstats_regularseason_subseason_shorthandedgoals') }} as  ls_reg_shorthanded_goals,
    {{ string_to_int('featuredstats_regularseason_subseason_shorthandedpoints') }} as  ls_reg_shorthanded_points,
    {{ string_to_int('featuredstats_regularseason_subseason_shots') }} as  ls_reg_shots,
    {{ string_to_int('featuredstats_regularseason_subseason_shutouts') }} as  ls_reg_shutouts,
    {{ string_to_int('featuredstats_regularseason_subseason_ties') }} as  ls_reg_ties,
    {{ string_to_int('featuredstats_regularseason_subseason_wins') }} as  ls_reg_wins
    from source
)
select * from renamed
