with source as (
        select * from {{ source('nhl_raw', 'raw_player_info') }}
  ),
renamed as (
    select
    {{ string_to_int('"playerId"') }} as player_id,
    "firstName.default" as first_name,
    "lastName.default" as last_name,
    "isActive":: bool as is_active,
    {{ string_to_int('"sweaterNumber"') }}  as jersey_number,
    "position",
    "headshot" as pic_url,
    "heroImage" as hero_pic_url,
    {{ string_to_int('"heightInInches"') }} as height_inches,
    {{ string_to_int('"weightInPounds"') }} as weight_pounds,
    {{ string_to_int('"heightInCentimeters"') }} as height_centimeters,
    {{ string_to_int('"weightInKilograms"') }} as weight_kg,
    TO_DATE("birthDate", 'YYYY-MM-DD') as birth_date,
    "birthCountry" as birth_country,
    "birthCity.default" as birth_city,
    "birthStateProvince.default" as birth_state,
    "shootsCatches" as shoots_or_catches,
    "inTop100AllTime"::bool as in_top100_alltime,
    "inHHOF":: bool as in_hall_of_game,
    {{ string_to_int('"featuredStats.season"') }} as latest_season,
    "currentTeamAbbrev" as current_team_id,
    {{ string_to_int('"draftDetails.overallPick"') }} as  draft_overall_pick,
    {{ string_to_int('"draftDetails.pickInRound"') }} as  draft_pickInRound,
    {{ string_to_int('"draftDetails.round"') }} as  draft_round,
    "draftDetails.teamAbbrev" as  draft_team_id,
    {{ string_to_int('"draftDetails.year"') }} as  draft_year,
    {{ string_to_int('"careerTotals.playoffs.assists"') }} as  career_pos_assists,
    {{ string_to_sec('"careerTotals.playoffs.avgToi"') }} as  career_pos_avg_timeonice_seconds, -- REVER
    {{ string_to_float('"careerTotals.playoffs.faceoffWinningPctg"') }} as  career_pos_faceoff_winning_pctg, -- REVER
    {{ string_to_int('"careerTotals.playoffs.gamesPlayed"') }} as  career_pos_games_played,
    {{ string_to_int('"careerTotals.playoffs.gamesStarted"') }} as  career_pos_games_started,
    {{ string_to_int('"careerTotals.playoffs.gameWinningGoals"') }} as  career_pos_game_winning_goals,
    {{ string_to_int('"careerTotals.playoffs.goals"') }} as  career_pos_goals,
    {{ string_to_int('"careerTotals.playoffs.goalsAgainst"') }} as  career_pos_goals_against,
    {{ string_to_float('"careerTotals.playoffs.goalsAgainstAvg"') }} as  career_pos_goals_against_avg,
    {{ string_to_int('"careerTotals.playoffs.losses"') }} as  career_pos_losses,
    {{ string_to_int('"careerTotals.playoffs.otGoals"') }} as  career_pos_ot_goals,
    {{ string_to_int('"careerTotals.playoffs.otLosses"') }} as  career_pos_ot_losses,
    {{ string_to_int('"careerTotals.playoffs.pim"') }} as  career_pos_pim,
    {{ string_to_int('"careerTotals.playoffs.plusMinus"') }} as  career_pos_plus_minus,
    {{ string_to_int('"careerTotals.playoffs.points"') }} as  career_pos_points,
    {{ string_to_int('"careerTotals.playoffs.powerPlayGoals"') }} as  career_pos_powerplay_goals,
    {{ string_to_int('"careerTotals.playoffs.powerPlayPoints"') }} as  career_pos_powerplay_points,
    {{ string_to_float('"careerTotals.playoffs.savePctg"') }} as  career_pos_save_pctg, -- REVER
    {{ string_to_float('"careerTotals.playoffs.shootingPctg"') }} as  career_pos_shooting_pctg, -- REVER
    {{ string_to_int('"careerTotals.playoffs.shorthandedGoals"') }} as  career_pos_shorthanded_goals,
    {{ string_to_int('"careerTotals.playoffs.shorthandedPoints"') }} as  career_pos_shorthanded_points,
    {{ string_to_int('"careerTotals.playoffs.shots"') }} as  career_pos_shots,
    {{ string_to_int('"careerTotals.playoffs.shotsAgainst"') }} as  career_pos_shotsagainst,
    {{ string_to_int('"careerTotals.playoffs.shutouts"') }} as  career_pos_shutouts,
    {{ string_to_int('"careerTotals.playoffs.ties"') }} as  career_pos_ties,
    {{ string_to_sec('"careerTotals.playoffs.timeOnIce"') }} as  career_pos_timeonice_seconds, -- REVER
    {{ string_to_int('"careerTotals.playoffs.wins"') }} as  career_pos_wins,
    {{ string_to_int('"careerTotals.regularSeason.assists"') }} as  career_reg_assists,
    {{ string_to_sec('"careerTotals.regularSeason.avgToi"') }} as  career_reg_avg_timeonice_seconds, -- REVER
    {{ string_to_float('"careerTotals.regularSeason.faceoffWinningPctg"') }} as  career_reg_faceoff_winning_pctg, -- REVER
    {{ string_to_int('"careerTotals.regularSeason.gamesPlayed"') }} as  career_reg_games_played,
    {{ string_to_int('"careerTotals.regularSeason.gamesStarted"') }} as  career_reg_games_started,
    {{ string_to_int('"careerTotals.regularSeason.gameWinningGoals"') }} as  career_reg_game_winning_goals,
    {{ string_to_int('"careerTotals.regularSeason.goals"') }} as  career_reg_goals,
    {{ string_to_int('"careerTotals.regularSeason.goalsAgainst"') }} as  career_reg_goals_against,
    {{ string_to_float('"careerTotals.regularSeason.goalsAgainstAvg"') }} as  career_reg_goals_against_avg,
    {{ string_to_int('"careerTotals.regularSeason.losses"') }} as  career_reg_losses,
    {{ string_to_int('"careerTotals.regularSeason.otGoals"') }} as  career_reg_ot_goals,
    {{ string_to_int('"careerTotals.regularSeason.otLosses"') }} as  career_reg_ot_losses,
    {{ string_to_int('"careerTotals.regularSeason.pim"') }} as  career_reg_pim,
    {{ string_to_int('"careerTotals.regularSeason.plusMinus"') }} as  career_reg_plus_minus,
    {{ string_to_int('"careerTotals.regularSeason.points"') }} as  career_reg_points,
    {{ string_to_int('"careerTotals.regularSeason.powerPlayGoals"') }} as  career_reg_powerplay_goals,
    {{ string_to_int('"careerTotals.regularSeason.powerPlayPoints"') }} as  career_reg_powerplay_points,
    {{ string_to_float('"careerTotals.regularSeason.savePctg"') }} as  career_reg_savepctg, -- REVER
    {{ string_to_float('"careerTotals.regularSeason.shootingPctg"') }} as  career_reg_shootingpctg, -- REVER
    {{ string_to_int('"careerTotals.regularSeason.shorthandedGoals"') }} as  career_reg_shorthanded_goals,
    {{ string_to_int('"careerTotals.regularSeason.shorthandedPoints"') }} as  career_reg_shorthanded_points,
    {{ string_to_int('"careerTotals.regularSeason.shots"') }} as  career_reg_shots,
    {{ string_to_int('"careerTotals.regularSeason.shotsAgainst"') }} as  career_reg_shots_against,
    {{ string_to_int('"careerTotals.regularSeason.shutouts"') }} as  career_reg_shutouts,
    {{ string_to_int('"careerTotals.regularSeason.ties"') }} as  career_reg_ties,
    {{ string_to_sec('"careerTotals.regularSeason.timeOnIce"') }} as  career_reg_timeonice_seconds, -- REVER
    {{ string_to_int('"careerTotals.regularSeason.wins"') }} as  career_reg_wins,
    {{ string_to_int('"featuredStats.playoffs.subSeason.assists"') }} as  ls_pos_assists,
    {{ string_to_int('"featuredStats.playoffs.subSeason.gamesPlayed"') }} as  ls_pos_games_played,
    {{ string_to_int('"featuredStats.playoffs.subSeason.gameWinningGoals"') }} as  ls_pos_game_winning_goals,
    {{ string_to_int('"featuredStats.playoffs.subSeason.goals"') }} as  ls_pos_goals,
    {{ string_to_float('"featuredStats.playoffs.subSeason.goalsAgainstAvg"') }} as  ls_pos_goals_against_avg,
    {{ string_to_int('"featuredStats.playoffs.subSeason.losses"') }} as  ls_pos_losses,
    {{ string_to_int('"featuredStats.playoffs.subSeason.otGoals"') }} as  ls_pos_ot_goals,
    {{ string_to_int('"featuredStats.playoffs.subSeason.otLosses"') }} as  ls_pos_ot_losses,
    {{ string_to_int('"featuredStats.playoffs.subSeason.pim"') }} as  ls_pos_pim,
    {{ string_to_int('"featuredStats.playoffs.subSeason.plusMinus"') }} as  ls_pos_plusminus,
    {{ string_to_int('"featuredStats.playoffs.subSeason.points"') }} as  ls_pos_points,
    {{ string_to_int('"featuredStats.playoffs.subSeason.powerPlayGoals"') }} as  ls_pos_powerplay_goals,
    {{ string_to_int('"featuredStats.playoffs.subSeason.powerPlayPoints"') }} as  ls_pos_powerplay_points,
    {{ string_to_float('"featuredStats.playoffs.subSeason.savePctg"') }} as  ls_pos_save_pctg, -- REVER
    {{ string_to_float('"featuredStats.playoffs.subSeason.shootingPctg"') }} as  ls_pos_shooting_pctg,
    {{ string_to_int('"featuredStats.playoffs.subSeason.shorthandedGoals"') }} as  ls_pos_shorthanded_goals,
    {{ string_to_int('"featuredStats.playoffs.subSeason.shorthandedPoints"') }} as  ls_pos_shorthanded_points,
    {{ string_to_int('"featuredStats.playoffs.subSeason.shots"') }} as  ls_pos_shots,
    {{ string_to_int('"featuredStats.playoffs.subSeason.shutouts"') }} as  ls_pos_shutouts,
    {{ string_to_int('"featuredStats.playoffs.subSeason.ties"') }} as  ls_pos_ties,
    {{ string_to_int('"featuredStats.playoffs.subSeason.wins"') }} as  ls_pos_wins,
    {{ string_to_int('"featuredStats.regularSeason.subSeason.assists"') }} as  ls_reg_assists,
    {{ string_to_int('"featuredStats.regularSeason.subSeason.gamesPlayed"') }} as  ls_reg_games_played,
    {{ string_to_int('"featuredStats.regularSeason.subSeason.gameWinningGoals"') }} as  ls_reg_game_winning_goals,
    {{ string_to_int('"featuredStats.regularSeason.subSeason.goals"') }} as  ls_reg_goals,
    {{ string_to_float('"featuredStats.regularSeason.subSeason.goalsAgainstAvg"') }} as  ls_reg_goals_against_avg,
    {{ string_to_int('"featuredStats.regularSeason.subSeason.losses"') }} as  ls_reg_losses,
    {{ string_to_int('"featuredStats.regularSeason.subSeason.otGoals"') }} as  ls_reg_ot_goals,
    {{ string_to_int('"featuredStats.regularSeason.subSeason.otLosses"') }} as  ls_reg_ot_losses,
    {{ string_to_int('"featuredStats.regularSeason.subSeason.pim"') }} as  ls_reg_pim,
    {{ string_to_int('"featuredStats.regularSeason.subSeason.plusMinus"') }} as  ls_reg_plusminus,
    {{ string_to_int('"featuredStats.regularSeason.subSeason.points"') }} as  ls_reg_points,
    {{ string_to_int('"featuredStats.regularSeason.subSeason.powerPlayGoals"') }} as  ls_reg_powerplay_goals,
    {{ string_to_int('"featuredStats.regularSeason.subSeason.powerPlayPoints"') }} as  ls_reg_powerplay_points,
    {{ string_to_float('"featuredStats.regularSeason.subSeason.savePctg"') }} as  ls_reg_save_pctg,
    {{ string_to_float('"featuredStats.regularSeason.subSeason.shootingPctg"') }} as  ls_reg_shooting_pctg, -- REVER
    {{ string_to_int('"featuredStats.regularSeason.subSeason.shorthandedGoals"') }} as  ls_reg_shorthanded_goals,
    {{ string_to_int('"featuredStats.regularSeason.subSeason.shorthandedPoints"') }} as  ls_reg_shorthanded_points,
    {{ string_to_int('"featuredStats.regularSeason.subSeason.shots"') }} as  ls_reg_shots,
    {{ string_to_int('"featuredStats.regularSeason.subSeason.shutouts"') }} as  ls_reg_shutouts,
    {{ string_to_int('"featuredStats.regularSeason.subSeason.ties"') }} as  ls_reg_ties,
    {{ string_to_int('"featuredStats.regularSeason.subSeason.wins"') }} as  ls_reg_wins
    from source
)
select * from renamed
