with source as (
        select * from {{ source('nhl_raw', 'raw_play_by_play') }}
  ),
  renamed as (
      select
          {{ string_to_int("eventid") }},
        "timeinperiod",
        make_time(0, substring(timeinperiod from 1 for 2)::integer, substring(timeinperiod from 4 for 2)::integer)::time AS time_in_period_time,
        make_time(0, substring(timeremaining from 1 for 2)::integer, substring(timeremaining from 4 for 2)::integer)::time AS time_remaining,
        {{ string_to_int("typecode") }} as type_code,
        "typedesckey",
        {{ string_to_int('"sortorder"') }} as sort_order,
        {{ string_to_int("perioddescriptor_number") }} as period_descr_number,
        "perioddescriptor_periodtype" as period_descr_type,
        {{ string_to_int("perioddescriptor_maxregulationperiods") }} as period_descr_max_regulation_periods,
        "details_typecode",
        "details_desckey",
        {{ string_to_int("details_duration") }} as details_duration,
        {{ string_to_int("details_committedbyplayerid") }} as details_committed_by_playerid,
        {{ string_to_int("details_eventownerteamid") }} as details_event_owner_teamid,
        {{ string_to_int("details_scoringplayerid") }} as details_scoring_playerid,
        {{ string_to_int("details_scoringplayertotal") }} as details_scoring_player_total,
        {{ string_to_int("details_goalieinnetid") }} as details_goalie_in_net_id,
        {{ string_to_int("details_awayscore") }} as details_away_score,
        {{ string_to_int("details_homescore") }} as details_home_score,
        {{ string_to_int("details_assist1playerid") }} as details_assist_1_player_id ,
        {{ string_to_int("details_assist1playertotal") }} as details_assist_1_player_total,
        {{string_to_int('SUBSTRING("filename" FROM 5 FOR 10)') }} AS game_id,
        {{ string_to_int("situationcode") }} as situation_code,
        {{ string_to_int("details_losingplayerid") }} as details_losing_player_id,
        {{ string_to_int("details_winningplayerid") }} as details_winning_player_id,
        {{ string_to_int("details_xcoord") }} as details_xcoord,
        {{ string_to_int("details_ycoord") }} as details_ycoord,
        details_zonecode,
        {{ string_to_int("details_hittingplayerid") }} as details_hitting_player_id ,
        {{ string_to_int("details_hitteeplayerid") }} as details_hittee_player_id,
        {{ string_to_int("details_blockingplayerid") }} as details_blocking_player_id,
        {{ string_to_int("details_shootingplayerid") }} as details_shooting_player_id,
        {{ string_to_int("details_playerid") }} as details_player_id,
        "details_reason",
        "details_shottype" as details_shot_type,
        {{ string_to_int("details_awaysog") }} as details_away_sog ,
        {{ string_to_int("details_homesog") }} as details_home_sog,
        "details_secondaryreason" as details_secondary_reason,
        {{ string_to_int("details_drawnbyplayerid") }} as details_drawnby_player_id,
        {{ string_to_int("details_assist2playerid") }} as details_assist_2_player_id,
        {{ string_to_int("details_assist2playertotal") }} as details_assist_2_player_total,
        {{ string_to_int("details_servedbyplayerid") }} as details_served_by_player_id,
        "hometeamdefendingside" as home_team_defending_side,
        "details_highlightclipsharingurl" as details_highlight_clip_sharing_url
      from source
  )
  select * from renamed
