with source as (
        select * from {{ source('nhl_raw','raw_game_details') }}
  ),
  renamed as (
      select
        SUBSTRING(filename FROM 5 FOR 10)::int as game_id,
        referee_1,
        referee_2,
        referee_3,
        {{ string_to_int('final_score_away') }} as away_score,
        {{ string_to_int('final_score_home') }} as home_score,
        {{ string_to_int('score_home_period_1') }} as home_score_period_1,
        {{ string_to_int('score_home_period_2') }} as home_score_period_2,
        {{ string_to_int('score_home_period_3') }} as home_score_period_3,
        {{ string_to_int('score_home_period_4') }} as home_score_period_4,
        {{ string_to_int('score_home_period_5') }} as home_score_period_5,
        {{ string_to_int('score_away_period_1') }} as away_score_period_1,
        {{ string_to_int('score_away_period_2') }} as away_score_period_2,
        {{ string_to_int('score_away_period_3') }} as away_score_period_3,
        {{ string_to_int('score_away_period_4') }} as away_score_period_4,
        {{ string_to_int('score_away_period_5') }} as away_score_period_5,
        {{ string_to_int('shots_home_period_1') }} as home_shots_period_1,
        {{ string_to_int('shots_home_period_2') }} as home_shots_period_2,
        {{ string_to_int('shots_home_period_3') }} as home_shots_period_3,
        {{ string_to_int('shots_home_period_4') }} as home_shots_period_4,
        {{ string_to_int('shots_home_period_5') }} as home_shots_period_5,
        {{ string_to_int('shots_away_period_1') }} as away_shots_period_1,
        {{ string_to_int('shots_away_period_2') }} as away_shots_period_2,
        {{ string_to_int('shots_away_period_3') }} as away_shots_period_3,
        {{ string_to_int('shots_away_period_4') }} as away_shots_period_4,
        {{ string_to_int('shots_away_period_5') }} as away_shots_period_5,
        {{ string_to_int('away_sog') }} as away_sog,
        {{ string_to_float('away_faceoffwinningpctg') }} as away_faceoff_winning_pctg,
        away_powerplay,
        {{ string_to_float('away_powerplaypctg') }} as away_powerplay_pctg,
        {{ string_to_int('away_pim') }} as away_penalty_minutes,
        {{ string_to_int('away_hits') }} as away_hits,
        {{ string_to_int('away_blockedshots') }} as away_blocked_shots,
        {{ string_to_int('away_giveaways') }} as away_giveaways,
        {{ string_to_int('away_takeaways') }} as away_takeaways,
        {{ string_to_int('home_sog') }} as home_sog,
        {{ string_to_float('home_faceoffwinningpctg') }} as home_faceoff_winning_pctg,
        home_powerplay,
        {{ string_to_float('home_powerplaypctg') }} as home_powerplay_pctg,
        {{ string_to_int('home_pim') }} as home_penalty_minutes,
        {{ string_to_int('home_hits') }} as home_hits,
        {{ string_to_int('home_blockedshots') }} as home_blocked_shots,
        {{ string_to_int('home_giveaways') }} as home_giveaways,
        {{ string_to_int('home_takeaways') }} as home_takeaways
      from source
  )
  select * from renamed
